language: go
go:
  - "1.15.x"
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

branches:
  only:
    - master
    - release

script:
  - make test
  - make testacc
  - make vet

deploy:
  provider: script
  script: ./scripts/release.sh
  on:
    branch: release
